# Generated by Django 6.0.7 on 2026-07-31 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("clinical", "0002_encounter_amended_at_alter_encounter_status_and_more"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprescriptionitem",
            name="advice_template",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="catalog.advicetemplate",
            ),
        ),
        migrations.AddField(
            model_name="historicalprescriptionitem",
            name="item_type",
            field=models.CharField(
                choices=[("MEDICATION", "Medication"), ("ADVICE", "Advice")],
                default="MEDICATION",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="historicalprescriptionitem",
            name="name_snapshot",
            field=models.CharField(default="", max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalprescriptionitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="advice_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prescription_items",
                to="catalog.advicetemplate",
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="item_type",
            field=models.CharField(
                choices=[("MEDICATION", "Medication"), ("ADVICE", "Advice")],
                default="MEDICATION",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="name_snapshot",
            field=models.CharField(default="", max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prescription_items",
                to="catalog.product",
            ),
        ),
        migrations.AlterField(
            model_name="historicalprescriptionitem",
            name="dosage",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="historicalprescriptionitem",
            name="free_text_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="prescriptionitem",
            name="dosage",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="prescriptionitem",
            name="free_text_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddConstraint(
            model_name="prescriptionitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("item_type", "MEDICATION"),
                        ("advice_template__isnull", True),
                        models.Q(
                            models.Q(
                                ("product__isnull", False), ("free_text_name", "")
                            ),
                            models.Q(
                                ("product__isnull", True),
                                models.Q(("free_text_name", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                    ),
                    models.Q(
                        ("item_type", "ADVICE"),
                        ("product__isnull", True),
                        models.Q(
                            models.Q(
                                ("advice_template__isnull", False),
                                ("free_text_name", ""),
                            ),
                            models.Q(
                                ("advice_template__isnull", True),
                                models.Q(("free_text_name", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="prescription_item_one_source_matching_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="prescriptionitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("item_type", "ADVICE"), _negated=True),
                    ("dosage__isnull", True),
                    _connector="OR",
                ),
                name="prescription_item_advice_has_no_dosage",
            ),
        ),
    ]
