# Generated by Django 6.0.7 on 2026-08-06 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinical", "0004_backfill_name_snapshot"),
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="encounter",
            name="appointment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="encounter",
                to="scheduling.appointment",
            ),
        ),
        migrations.AddField(
            model_name="historicalencounter",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="scheduling.appointment",
            ),
        ),
    ]
