# Generated by Django 6.0.7 on 2026-08-15 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_product_default_strength"),
        ("clinical", "0006_encounterphoto"),
        ("organizations", "0005_organization_strength_enabled_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprescriptionitem",
            name="strength",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="strength",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddConstraint(
            model_name="prescriptionitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("item_type", "ADVICE"), _negated=True),
                    ("strength", ""),
                    _connector="OR",
                ),
                name="prescription_item_advice_has_no_strength",
            ),
        ),
    ]
