# Generated by Django 6.0.7 on 2026-08-21 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_product_default_strength"),
        ("clinical", "0007_historicalprescriptionitem_strength_and_more"),
        ("organizations", "0006_organization_pack_size_enabled_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprescriptionitem",
            name="pack_size",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="historicalprescriptionitem",
            name="preparation",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="pack_size",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="preparation",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddConstraint(
            model_name="prescriptionitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("item_type", "ADVICE"), _negated=True),
                    ("pack_size", ""),
                    _connector="OR",
                ),
                name="prescription_item_advice_has_no_pack_size",
            ),
        ),
        migrations.AddConstraint(
            model_name="prescriptionitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("item_type", "ADVICE"), _negated=True),
                    ("preparation", ""),
                    _connector="OR",
                ),
                name="prescription_item_advice_has_no_preparation",
            ),
        ),
    ]
