# Generated by Django 6.0.7 on 2026-08-06 22:35

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clinical", "0004_backfill_name_snapshot"),
        ("organizations", "0004_organization_advice_enabled"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scheduled_date", models.DateField(db_index=True)),
                ("scheduled_time", models.TimeField(blank=True, null=True)),
                (
                    "day_part",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MORNING", "Morning"),
                            ("AFTERNOON", "Afternoon"),
                            ("EVENING", "Evening"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("BOOKED", "Booked"), ("WALK_IN", "Walk-in")],
                        default="BOOKED",
                        max_length=8,
                    ),
                ),
                ("arrived_at", models.DateTimeField(blank=True, null=True)),
                ("seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[("NO_SHOW", "No show"), ("CANCELLED", "Cancelled")],
                        max_length=10,
                    ),
                ),
                ("resolution_reason", models.CharField(blank=True, max_length=300)),
                ("note", models.CharField(blank=True, max_length=300)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="organizations.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
                (
                    "origin_encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="follow_up_appointments",
                        to="clinical.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="patients.patient",
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_date", "scheduled_time"],
                "base_manager_name": "all_objects",
                "indexes": [
                    models.Index(
                        fields=["organization", "scheduled_date"],
                        name="scheduling__organiz_cb51c1_idx",
                    ),
                    models.Index(
                        fields=["organization", "branch", "scheduled_date"],
                        name="scheduling__organiz_a61d53_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("scheduled_time__isnull", False),
                            models.Q(("day_part", ""), _negated=True),
                            _negated=True,
                        ),
                        name="appointment_time_xor_day_part",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("source", "WALK_IN"),
                            ("arrived_at__isnull", True),
                            _negated=True,
                        ),
                        name="appointment_walk_in_has_arrived",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("seen_at__isnull", False),
                            ("arrived_at__isnull", True),
                            _negated=True,
                        ),
                        name="appointment_seen_after_arrival",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("seen_at__isnull", False),
                            models.Q(("resolution", ""), _negated=True),
                            _negated=True,
                        ),
                        name="appointment_seen_xor_resolved",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("resolution", ""),
                            models.Q(("resolution_reason", ""), _negated=True),
                            _negated=True,
                        ),
                        name="appointment_reason_needs_resolution",
                    ),
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
