# Generated by Django 6.0.7 on 2026-08-04 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
        ("organizations", "0003_organization_default_consultation_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinvoice",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="organizations.branch",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="organizations.branch",
            ),
        ),
    ]
