# Generated by Django 6.0.7 on 2026-08-04 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_historicalinvoice_branch_invoice_branch"),
        ("catalog", "0003_product_reorder_level_alter_product_is_stock_tracked"),
        ("inventory", "0001_initial"),
        ("organizations", "0003_organization_default_consultation_fee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinvoiceitem",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.stockbatch",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_items",
                to="inventory.stockbatch",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("batch__isnull", True), ("product__isnull", False), _connector="OR"
                ),
                name="invoice_item_batch_only_with_product",
            ),
        ),
    ]
