# Generated by Django 6.0.7 on 2026-08-01 14:52

import organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="terminology",
            field=models.JSONField(
                blank=True, default=organizations.models.default_terminology
            ),
        ),
    ]
