# Generated by Django 6.0.7 on 2026-08-02 20:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_organization_terminology"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="default_consultation_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Prefilled on the consultation line of a new bill.",
                max_digits=12,
            ),
        ),
    ]
