# Generated by Django 6.0.7 on 2026-08-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_organization_default_consultation_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="advice_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Offer structured advice alongside medicines when prescribing.",
            ),
        ),
    ]
