# Generated by Django 6.0.7 on 2026-08-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0004_organization_advice_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="strength_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Record how strong each prescribed preparation is.",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="strength_options",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Suggested values, offered but never enforced.",
            ),
        ),
    ]
