# Generated by Django 6.0.7 on 2026-08-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0005_organization_strength_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="pack_size_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Record how much of each medicine goes home with the patient.",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="pack_size_options",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Suggested values, offered but never enforced.",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="preparation_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Record the physical preparation each medicine is dispensed as.",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="preparation_options",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Suggested values, offered but never enforced.",
            ),
        ),
    ]
