# Generated by Django 6.0.7 on 2026-08-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0006_organization_pack_size_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="consulting_hours",
            field=models.CharField(
                blank=True,
                help_text="Printed in the header when a visit happens here.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="print_order",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Lower numbers print first."
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="schedule_note",
            field=models.CharField(
                blank=True,
                help_text="Printed in the footer, e.g. every 2nd Friday of the month.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="show_on_prescription",
            field=models.BooleanField(
                default=False,
                help_text="List this chamber in the footer of printed prescriptions.",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="prescription_contacts",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="One per line, printed along the foot of the prescription.",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="prescription_notice",
            field=models.TextField(
                blank=True, help_text="Printed across the foot of every prescription."
            ),
        ),
    ]
