# Generated by Django 6.0.7 on 2026-08-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0007_branch_consulting_hours_branch_print_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="billing_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Raise bills, take payments, and print receipts.",
            ),
        ),
    ]
