# Generated by Django 6.0.7 on 2026-08-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0008_organization_billing_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="temperature_unit",
            field=models.CharField(
                choices=[("F", "Fahrenheit (°F)"), ("C", "Celsius (°C)")],
                default="F",
                help_text="The unit temperatures are entered and shown in.",
                max_length=1,
            ),
        ),
    ]
