# Generated by Django 6.0.7 on 2026-08-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0009_organization_temperature_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="case_record_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Take a full structured case history for each patient.",
            ),
        ),
    ]
