# Generated by Django 6.0.7 on 2026-08-30 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0010_organization_case_record_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="is_default",
            field=models.BooleanField(
                default=False, help_text="Preselected on a new visit."
            ),
        ),
        migrations.AddConstraint(
            model_name="branch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("organization", "is_default"),
                name="branch_one_default_per_org",
            ),
        ),
    ]
