# Generated by Django 6.0.7 on 2026-09-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0011_branch_is_default_branch_branch_one_default_per_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="prescription_sizes",
            field=models.CharField(
                choices=[("BOTH", "A5 and A4"), ("A5", "A5 only"), ("A4", "A4 only")],
                default="BOTH",
                help_text="Which paper sizes the printed prescription offers.",
                max_length=4,
            ),
        ),
    ]
