# Generated by Django 6.0.7 on 2026-08-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("OWNER", "Administrator"),
                    ("PRACTITIONER", "Practitioner"),
                    ("STAFF", "Staff"),
                ],
                default="STAFF",
                max_length=20,
            ),
        ),
    ]
