# Generated by Django 6.0.7 on 2026-08-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_must_change_password_alter_membership_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("OWNER", "Administrator"),
                    ("PRACTITIONER", "Practitioner"),
                    ("STAFF", "Staff"),
                    ("DEVELOPER", "Developer"),
                ],
                default="STAFF",
                max_length=20,
            ),
        ),
    ]
