# Generated by Django 6.0.7 on 2026-08-28 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_membership_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="PractitionerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "print_name",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to print the name on the account.",
                        max_length=200,
                    ),
                ),
                ("degrees", models.CharField(blank=True, max_length=200)),
                ("designation", models.TextField(blank=True)),
                ("additional_note", models.TextField(blank=True)),
                ("registration_number", models.CharField(blank=True, max_length=40)),
                ("contact_phone", models.CharField(blank=True, max_length=32)),
                (
                    "membership",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practitioner_profile",
                        to="accounts.membership",
                    ),
                ),
            ],
            options={
                "verbose_name": "practitioner profile",
            },
        ),
    ]
