# Generated by Django 6.0.7 on 2026-08-04 05:00

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("catalog", "0002_product_sale_price"),
        ("clinical", "0004_backfill_name_snapshot"),
        ("organizations", "0003_organization_default_consultation_fee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodsReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(editable=False, max_length=32)),
                ("supplier", models.CharField(blank=True, max_length=200)),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="The supplier's own invoice number.",
                        max_length=64,
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_receipts",
                        to="organizations.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at", "-id"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="StockBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lot_number", models.CharField(blank=True, max_length=64)),
                ("expiry_date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=300)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="organizations.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["expiry_date", "id"],
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="GoodsReceiptItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_receipt_items",
                        to="catalog.product",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.goodsreceipt",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_receipt_items",
                        to="inventory.stockbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "Purchase"),
                            ("SALE", "Sale"),
                            ("DISPENSE", "Dispense"),
                            ("ADJUSTMENT", "Adjustment"),
                            ("RETURN", "Return"),
                            ("WASTAGE", "Wastage"),
                        ],
                        max_length=12,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=300)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.stockbatch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "goods_receipt_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.goodsreceiptitem",
                    ),
                ),
                (
                    "invoice_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="billing.invoiceitem",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
                (
                    "prescription_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="clinical.prescriptionitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="goodsreceipt",
            index=models.Index(
                fields=["organization", "-received_at"],
                name="inventory_g_organiz_2fa850_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="goodsreceipt",
            constraint=models.UniqueConstraint(
                fields=("organization", "number"),
                name="goods_receipt_number_unique_per_org",
            ),
        ),
        migrations.AddIndex(
            model_name="stockbatch",
            index=models.Index(
                fields=["organization", "product", "branch"],
                name="inventory_s_organiz_981093_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockbatch",
            index=models.Index(
                fields=["organization", "expiry_date"],
                name="inventory_s_organiz_52c50b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbatch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("lot_number", ""), _negated=True),
                fields=("organization", "product", "branch", "lot_number"),
                name="stock_batch_lot_unique_per_product_branch",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("cost_price__gte", 0)),
                name="stock_batch_cost_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="goodsreceiptitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="goods_receipt_item_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="goodsreceiptitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("cost_price__gte", 0)),
                name="goods_receipt_item_cost_not_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["organization", "-occurred_at"],
                name="inventory_s_organiz_b34dbc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["organization", "batch"], name="inventory_s_organiz_a4759d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("movement_type__in", ["PURCHASE", "RETURN"]),
                        ("quantity__gt", 0),
                    ),
                    models.Q(
                        ("movement_type__in", ["SALE", "DISPENSE", "WASTAGE"]),
                        ("quantity__lt", 0),
                    ),
                    models.Q(
                        ("movement_type", "ADJUSTMENT"),
                        models.Q(("quantity", 0), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="stock_movement_quantity_sign_matches_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("goods_receipt_item__isnull", True),
                        ("invoice_item__isnull", True),
                        ("prescription_item__isnull", True),
                    ),
                    models.Q(
                        ("goods_receipt_item__isnull", False),
                        ("invoice_item__isnull", True),
                        ("movement_type", "PURCHASE"),
                        ("prescription_item__isnull", True),
                    ),
                    models.Q(
                        ("goods_receipt_item__isnull", True),
                        ("invoice_item__isnull", False),
                        ("movement_type", "SALE"),
                        ("prescription_item__isnull", True),
                    ),
                    models.Q(
                        ("goods_receipt_item__isnull", True),
                        ("invoice_item__isnull", True),
                        ("movement_type", "DISPENSE"),
                        ("prescription_item__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="stock_movement_source_matches_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("movement_type__in", ["ADJUSTMENT", "WASTAGE"]), _negated=True
                    ),
                    models.Q(("reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="stock_movement_correction_has_reason",
            ),
        ),
    ]
