# Generated by Django 6.0.7 on 2026-08-04 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_historicalinvoiceitem_batch_invoiceitem_batch_and_more"),
        ("clinical", "0004_backfill_name_snapshot"),
        ("inventory", "0001_initial"),
        ("organizations", "0003_organization_default_consultation_fee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="stockmovement",
            name="stock_movement_source_matches_type",
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("goods_receipt_item__isnull", True),
                        ("invoice_item__isnull", True),
                        ("prescription_item__isnull", True),
                    ),
                    models.Q(
                        ("goods_receipt_item__isnull", False),
                        ("invoice_item__isnull", True),
                        ("movement_type", "PURCHASE"),
                        ("prescription_item__isnull", True),
                    ),
                    models.Q(
                        ("goods_receipt_item__isnull", True),
                        ("invoice_item__isnull", False),
                        ("movement_type", "SALE"),
                        ("prescription_item__isnull", True),
                    ),
                    models.Q(
                        ("goods_receipt_item__isnull", True),
                        ("invoice_item__isnull", False),
                        ("movement_type", "RETURN"),
                        ("prescription_item__isnull", True),
                    ),
                    models.Q(
                        ("goods_receipt_item__isnull", True),
                        ("invoice_item__isnull", True),
                        ("movement_type", "DISPENSE"),
                        ("prescription_item__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="stock_movement_source_matches_type",
            ),
        ),
    ]
