# Generated by Django 6.0.7 on 2026-07-31 21:26

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdviceTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("DIET", "Diet"),
                            ("EXERCISE", "Exercise"),
                            ("SLEEP", "Sleep"),
                            ("LIFESTYLE", "Lifestyle"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("default_frequency", models.CharField(blank=True, max_length=100)),
                ("default_duration", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "text"],
                "indexes": [
                    models.Index(
                        fields=["organization", "category"],
                        name="catalog_adv_organiz_02732f_idx",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("sku", models.CharField(blank=True, max_length=50)),
                (
                    "category",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Tablet, capsule, ml, drops, …",
                        max_length=50,
                    ),
                ),
                ("default_attributes", models.JSONField(blank=True, default=dict)),
                (
                    "is_stock_tracked",
                    models.BooleanField(
                        default=False,
                        help_text="Reserved for inventory; no stock is tracked yet.",
                    ),
                ),
                (
                    "is_sellable",
                    models.BooleanField(
                        default=False,
                        help_text="False for things recommended but not dispensed here.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["organization", "name"],
                        name="catalog_pro_organiz_ffc1ba_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("sku", ""), _negated=True),
                        fields=("organization", "sku"),
                        name="product_sku_unique_per_org",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
