# Generated by Django 6.0.7 on 2026-08-02 20:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sale_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Prefilled when this is added to a bill.",
                max_digits=12,
            ),
        ),
    ]
