# Generated by Django 6.0.7 on 2026-08-04 06:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_product_sale_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="reorder_level",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Warn when stock falls to or below this. Zero means no alert.",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_stock_tracked",
            field=models.BooleanField(
                default=False, help_text="Count this product in and out of stock."
            ),
        ),
    ]
