# Generated by Django 6.0.7 on 2026-08-06 21:08

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_product_reorder_level_alter_product_is_stock_tracked"),
        ("organizations", "0003_organization_default_consultation_fee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="advicetemplate",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("text"),
                models.F("organization"),
                name="advice_text_unique_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("organization"),
                name="product_name_unique_per_org",
            ),
        ),
    ]
