# Generated by Django 6.0.7 on 2026-08-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_advicetemplate_advice_text_unique_per_org_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_sellable",
            field=models.BooleanField(
                default=True,
                help_text="Untick for things recommended but not dispensed here.",
            ),
        ),
    ]
