# Generated by Django 6.0.7 on 2026-08-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_alter_product_is_sellable"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="default_strength",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
