# Generated by Django 6.0.7 on 2026-08-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="alt_phone",
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name="patient",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="patient",
            name="marital_status",
            field=models.CharField(
                choices=[
                    ("S", "Single"),
                    ("M", "Married"),
                    ("W", "Widowed"),
                    ("D", "Divorced"),
                    ("O", "Other"),
                    ("U", "Not recorded"),
                ],
                default="U",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="occupation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="patient",
            name="referred_by",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
